name: 'PR Notion Version Action'
description: 'Insert a release version into a Notion database'
inputs:
  notion-api-token:
    required: true
  notion-database-id:
    description: 'The ID of the Notion database to insert the release version into'
    required: true
  # TODO: somehow make this more dynamic for different databases with different properties
  release-version:
    description: 'The release version to insert into the Notion database'
    required: true
  release-date:
    description: 'The release date to insert into the Notion database'
    required: true
runs:
  using: 'node20'
  main: 'index.js'
